const node = (number: string, label: string, kind: string) => `<div class="node ${kind}"><span>${number}</span><strong>${label}</strong></div>`;
const arrow = `<span class="arrow" aria-hidden="true">→</span>`;

export const FIGURE_CSS = `
  .figure{margin:25px 0;border:1px solid var(--line);border-radius:18px;background:#fff;padding:21px}.figure header{margin-bottom:15px}.figure .kicker{color:var(--red);font:800 11px/1 var(--sans);letter-spacing:.1em;text-transform:uppercase}.figure h2{margin:6px 0 0;font:750 20px/1.2 var(--display)}.flow{display:flex;align-items:stretch;min-width:max-content}.scroll{overflow-x:auto;padding-bottom:6px}.node{position:relative;display:flex;flex-direction:column;justify-content:center;width:165px;min-height:82px;border:1px solid var(--line);border-radius:12px;background:#fafafa;padding:14px;text-align:center;color:var(--ink);font:650 13px/1.35 var(--sans)}.node span{position:absolute;top:8px;left:9px;color:var(--muted);font:700 10px/1 var(--mono)}.node.source{border-color:#aaa;background:#f6f6f6}.node.deck{border-color:#e69b9b;background:#fff0f0}.node.page{border-color:#d44646;background:#ed1c24;color:#fff}.arrow{display:flex;align-items:center;padding:0 9px;color:var(--muted);font-size:23px}.figure p{margin:14px 0 0;color:var(--ink);font-weight:650}@media(max-width:680px){.figure{padding:16px}.node{width:142px}.arrow{padding:0 6px}}`;

export const FIGURES: Record<string, string> = {
  "deck-flow": `<figure class="figure" aria-labelledby="deck-flow-title"><header><div class="kicker">Deck architecture</div><h2 id="deck-flow-title">Five slides move from the sales problem to proof.</h2></header><div class="scroll"><div class="flow">${node("01", "Sales problem", "source")}${arrow}${node("02", "Databricks evidence", "source")}${arrow}${node("03", "Kimi agent", "deck")}${arrow}${node("04", "Human approval", "deck")}${arrow}${node("05", "Proof links", "deck")}</div></div><p>The deck has five slides: sales problem, Databricks evidence, Kimi agent, human approval, and proof links.</p></figure>`,
  "publish-flow": `<figure class="figure" aria-labelledby="publish-flow-title"><header><div class="kicker">Publish boundary</div><h2 id="publish-flow-title">Only the slide payload reaches the public branch.</h2></header><div class="scroll"><div class="flow">${node("01", "Source repository", "source")}${arrow}${node("02", "Static slides payload", "deck")}${arrow}${node("03", "gh-pages branch root", "page")}${arrow}${node("04", "GitHub Pages", "page")}</div></div><p>The dedicated gh-pages branch contains only this directory's contents. GitHub Pages serves the branch root.</p></figure>`,
};
